# Generated by Django 2.2.2 on 2020-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200310_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='count_submit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
